name: Publish Website

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 3

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'
    - name: Cache Dependencies
      uses: actions/cache@v2
      id: cache-node
      with:
        path: |
          ./node_modules
        key: cache-node
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install git+https://github.com/pjb7687/scholarly.git@sortbydate
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install Node.js Dependencies
      run: npm install
      if: steps.cache-node.outputs.cache-hit != 'true'
    - name: Fetch Google Scholar Citations
      run: |
        python .ci/get_citations.py
    - name: Build Website
      run: |
        npm run sass
        sphinx-build -a source build
        touch build/.nojekyll
        echo "jeongbinpark.com" > build/CNAME
    - name: Commit and Push Caches
      uses: EndBug/add-and-commit@v7
      with:
        branch: 'source'
        message: 'update cache files'
    - name: Deploy Website
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
        CLEAN: true
