name: Publish Website

on:
  workflow_dispatch:
  schedule:
    - cron: 0 20 * * *

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: |
          ./venv
          ./node_modules
        key: cache-venv-node
    - name: Install Python Dependencies
      run: |
        python -m venv ./venv && . ./venv/bin/activate
        python -m pip install --upgrade pip
        pip install sphinx numpy pandas pdfminer.six
        pip install git+https://github.com/pjb7687/scholarly.git@sortbydate
      if: steps.cache-venv-node.outputs.cache-hit != 'true'
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install Node.js Dependencies
      run: npm install
      if: steps.cache-venv-node.outputs.cache-hit != 'true'
    - name: Build
      run: |
        python -m venv ./venv && . ./venv/bin/activate
        npm run sass
        bash .ci/build.sh
        touch build/.nojekyll
        echo "jeongbinpark.com" > build/CNAME
    - name: Deploy Website
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
        CLEAN: true
    - name: Commit and Push Caches
      uses: github-actions-x/commit@v2.7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'source'
        commit-message: 'update cache files'
        files: .ci/gscache.txt source/_static/hd_stats.json source/_static/rnk_stats.json
